#!/usr/bin/env bun
/**
 * Refresh src/catalog.generated.ts from `cursor-agent models`.
 *
 * The CLI is the catalog source of truth: its ids already encode the
 * reasoning level (`-thinking`, `-high`, `-xhigh`), so they are registered
 * verbatim. Context windows stay in the hand-maintained table below the
 * model list; unknown families fall back to 200k at runtime.
 */
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { parseAgentModels } from "../../../../src/models.js";

const CATALOG_PATH = new URL("../../../../src/catalog.generated.ts", import.meta.url).pathname;
const agentBinary = process.env.CURSOR_AGENT_PATH?.trim() || process.env.AGENT_PATH?.trim() || "cursor-agent";

const result = spawnSync(agentBinary, ["models"], { encoding: "utf8", timeout: 60_000 });
if (result.error) {
  console.error(`cursor-agent models failed: ${result.error.message}`);
  process.exit(1);
}
const models = parseAgentModels(result.stdout ?? "");
if (models.length === 0) {
  console.error("cursor-agent models returned no models; keeping the existing catalog");
  console.error(result.stderr?.trim() ?? "");
  process.exit(1);
}

const previous = readFileSync(CATALOG_PATH, "utf8");
const windowsMatch = /export const CURSOR_CONTEXT_WINDOWS: Record<string, number> = \{(?<body>[\s\S]*?)\n\};/.exec(previous);
const windows = windowsMatch?.groups?.body ?? "";

const lines = [
  "// Generated by the update-catalog skill from `cursor-agent models`. Do not edit by hand.",
  "",
  "export interface CursorCliModelItem {",
  "  id: string;",
  "  name: string;",
  "}",
  "",
  "export const FALLBACK_CLI_MODELS: readonly CursorCliModelItem[] = [",
  ...models.map((model) => `  { id: ${JSON.stringify(model.id)}, name: ${JSON.stringify(model.name)} },`),
  "];",
  "",
  `export const CURSOR_CONTEXT_WINDOWS: Record<string, number> = {${windows}\n};`,
  "",
];

writeFileSync(CATALOG_PATH, lines.join("\n"));
console.log(`catalog.generated.ts refreshed with ${models.length} models`);
