import type { ModelListItem } from "@cursor/sdk";

// Generated by `.omp/skills/update-catalog`. Do not edit by hand.
export const CATALOG_GENERATED_AT = "2026-08-16T10:56:31.769Z";
export const CATALOG_SOURCE = "Cursor.models.list";

function catalogParam(id: string, values: readonly string[]) {
  return { id, values: values.map((value) => ({ value })) };
}

export const FALLBACK_CATALOG_ITEMS: readonly ModelListItem[] = [
  {
    id: "claude-fable-5",
    displayName: "Fable 5",
    parameters: [
      catalogParam("thinking", ["false", "true"]),
      catalogParam("context", ["300k", "1m"]),
      catalogParam("effort", ["low", "medium", "high", "xhigh", "max"]),
    ],
  },
  {
    id: "claude-haiku-4-5",
    displayName: "Haiku 4.5",
    parameters: [catalogParam("thinking", ["false", "true"])],
  },
  {
    id: "claude-opus-4-5",
    displayName: "Opus 4.5",
    parameters: [catalogParam("thinking", ["false", "true"])],
  },
  {
    id: "claude-opus-4-6",
    displayName: "Opus 4.6",
    parameters: [
      catalogParam("thinking", ["false", "true"]),
      catalogParam("context", ["200k", "1m"]),
      catalogParam("effort", ["low", "medium", "high", "max"]),
    ],
  },
  {
    id: "claude-opus-4-7",
    displayName: "Opus 4.7",
    parameters: [
      catalogParam("thinking", ["false", "true"]),
      catalogParam("context", ["300k", "1m"]),
      catalogParam("effort", ["low", "medium", "high", "xhigh", "max"]),
    ],
  },
  {
    id: "claude-opus-4-8",
    displayName: "Opus 4.8",
    parameters: [
      catalogParam("thinking", ["false", "true"]),
      catalogParam("context", ["300k", "1m"]),
      catalogParam("effort", ["low", "medium", "high", "xhigh", "max"]),
    ],
  },
  {
    id: "claude-opus-5",
    displayName: "Opus 5",
    parameters: [
      catalogParam("thinking", ["false", "true"]),
      catalogParam("context", ["300k", "1m"]),
      catalogParam("effort", ["low", "medium", "high", "xhigh", "max"]),
    ],
  },
  {
    id: "claude-sonnet-4",
    displayName: "Sonnet 4",
    parameters: [catalogParam("thinking", ["false", "true"]), catalogParam("context", ["200k"])],
  },
  {
    id: "claude-sonnet-4-5",
    displayName: "Sonnet 4.5",
    parameters: [catalogParam("thinking", ["false", "true"]), catalogParam("context", ["200k"])],
  },
  {
    id: "claude-sonnet-4-6",
    displayName: "Sonnet 4.6",
    parameters: [
      catalogParam("thinking", ["false", "true"]),
      catalogParam("context", ["200k", "1m"]),
      catalogParam("effort", ["low", "medium", "high", "max"]),
    ],
  },
  {
    id: "claude-sonnet-5",
    displayName: "Sonnet 5",
    parameters: [
      catalogParam("thinking", ["false", "true"]),
      catalogParam("context", ["300k", "1m"]),
      catalogParam("effort", ["low", "medium", "high", "xhigh", "max"]),
    ],
  },
  { id: "composer-2", displayName: "Composer 2" },
  { id: "composer-2.5", displayName: "Composer 2.5" },
  { id: "default", displayName: "Auto" },
  { id: "gemini-2.5-flash", displayName: "Gemini 2.5 Flash" },
  { id: "gemini-3-flash", displayName: "Gemini 3 Flash" },
  { id: "gemini-3.1-pro", displayName: "Gemini 3.1 Pro" },
  { id: "gemini-3.5-flash", displayName: "Gemini 3.5 Flash" },
  {
    id: "gemini-3.6-flash",
    displayName: "Gemini 3.6 Flash",
    parameters: [catalogParam("effort", ["minimal", "low", "medium", "high"])],
  },
  {
    id: "gemini-3.7-flash",
    displayName: "Gemini 3.7 Flash",
    parameters: [catalogParam("effort", ["low", "medium", "high"])],
  },
  {
    id: "glm-5.2",
    displayName: "GLM 5.2",
    parameters: [catalogParam("reasoning", ["high", "max"])],
  },
  { id: "gpt-5-mini", displayName: "GPT-5 Mini" },
  {
    id: "gpt-5.1",
    displayName: "GPT-5.1",
    parameters: [catalogParam("reasoning", ["low", "medium", "high"])],
  },
  {
    id: "gpt-5.2",
    displayName: "GPT-5.2",
    parameters: [catalogParam("reasoning", ["low", "medium", "high", "extra-high"])],
  },
  {
    id: "gpt-5.3-codex",
    displayName: "Codex 5.3",
    parameters: [catalogParam("reasoning", ["low", "medium", "high", "extra-high"])],
  },
  {
    id: "gpt-5.4",
    displayName: "GPT-5.4",
    parameters: [
      catalogParam("context", ["272k", "1m"]),
      catalogParam("reasoning", ["none", "low", "medium", "high", "extra-high"]),
    ],
  },
  {
    id: "gpt-5.4-mini",
    displayName: "GPT-5.4 Mini",
    parameters: [catalogParam("reasoning", ["none", "low", "medium", "high", "xhigh"])],
  },
  {
    id: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano",
    parameters: [catalogParam("reasoning", ["none", "low", "medium", "high", "xhigh"])],
  },
  {
    id: "gpt-5.5",
    displayName: "GPT-5.5",
    parameters: [
      catalogParam("context", ["272k", "1m"]),
      catalogParam("reasoning", ["none", "low", "medium", "high", "extra-high"]),
    ],
  },
  {
    id: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    parameters: [
      catalogParam("context", ["272k", "1m"]),
      catalogParam("reasoning", ["none", "low", "medium", "high", "xhigh", "max"]),
    ],
  },
  {
    id: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    parameters: [
      catalogParam("context", ["272k", "1m"]),
      catalogParam("reasoning", ["none", "low", "medium", "high", "xhigh", "max"]),
    ],
  },
  {
    id: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    parameters: [
      catalogParam("context", ["272k", "1m"]),
      catalogParam("reasoning", ["none", "low", "medium", "high", "xhigh", "max"]),
    ],
  },
  {
    id: "grok-4.5",
    displayName: "Cursor Grok 4.5",
    parameters: [catalogParam("effort", ["low", "medium", "high"])],
  },
  {
    id: "grok-4.6",
    displayName: "Cursor Grok 4.6",
    parameters: [catalogParam("effort", ["low", "medium", "high", "xhigh"])],
  },
  { id: "kimi-k2.7-code", displayName: "Kimi K2.7 Code" },
  {
    id: "kimi-k3",
    displayName: "Kimi K3",
    parameters: [catalogParam("reasoning", ["low", "high", "max"])],
  },
];

export const CURSOR_CONTEXT_WINDOWS: Record<string, number> = {
  "claude-fable-5": 1_000_000,
  "claude-haiku-4-5": 200_000,
  "claude-opus-4-5": 200_000,
  "claude-opus-4-6": 1_000_000,
  "claude-opus-4-7": 1_000_000,
  "claude-opus-4-8": 1_000_000,
  "claude-opus-5": 1_000_000,
  "claude-sonnet-4": 200_000,
  "claude-sonnet-4-5": 200_000,
  "claude-sonnet-4-6": 1_000_000,
  "claude-sonnet-5": 1_000_000,
  "composer-2": 200_000,
  "composer-2.5": 200_000,
  default: 200_000,
  "gemini-2.5-flash": 200_000,
  "gemini-3-flash": 200_000,
  "gemini-3.1-pro": 200_000,
  "gemini-3.5-flash": 200_000,
  "gemini-3.6-flash": 200_000,
  "gemini-3.7-flash": 200_000,
  "glm-5.2": 200_000,
  "gpt-5-mini": 272_000,
  "gpt-5.1": 272_000,
  "gpt-5.2": 272_000,
  "gpt-5.3-codex": 272_000,
  "gpt-5.4": 1_000_000,
  "gpt-5.4-mini": 272_000,
  "gpt-5.4-nano": 272_000,
  "gpt-5.5": 1_000_000,
  "gpt-5.6-luna": 1_000_000,
  "gpt-5.6-sol": 1_000_000,
  "gpt-5.6-terra": 1_000_000,
  "grok-4.5": 200_000,
  "grok-4.6": 256_000,
  "kimi-k2.7-code": 200_000,
  "kimi-k3": 200_000,
};
